production:
  adapter: mysql2
  database: redmine_tmp
  host: donow.jp
  username: redmine_tmp_user
  password: redmine_tmp_pass
  # Use "utf8" instead of "utfmb4" for MySQL prior to 5.7.7
  encoding: utf8
